login2/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "users/sign_up"
  get "users/sign_in" => 'sessions#new'
  resources :users

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  root 'posts#index'

  resources :posts do
  	resources :comments
  end

  post '/' => 'posts#create'

end

login2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

login2/app/models/comment.rb
class Comment < ApplicationRecord
	validates :content, presence: true
	belongs_to :post
end

login2/app/models/post.rb
class Post < ApplicationRecord
	validates :content, presence:true
	belongs_to :user
	has_many :comments, dependent: :destroy
end

login2/app/models/user.rb
class User < ApplicationRecord
	validates_presence_of :first_name, :last_name
	validates_uniqueness_of :email
	validates :email, :email_format => { :message => 'is not looking good' }
	validates :password, length: { minimum: 6 }

	has_many :posts
end

login2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

login2/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def index
		@comments = Post.find(params[:post_id]).comments.all
		@comment = Comment.new
		@post = Post.find(params[:post_id])
		@user = @post.user
		@current_user = current_user()
	end

	def new
		@comment = Comment.new
	end

	def show
		@comment = Post.find(params[:post_id]).comments.find(params[:id])
	end

	def create
	    @post = Post.find(params[:post_id])
	    @comment = @post.comments.new(comment_params)
	    if (@comment.save)
	    	redirect_to post_comments_path(@post)
	    else
	    	render 'index'
	    end
  	end

  	def current_user
  		User.find(session[:user_id])
  	end

  	private 
  	def comment_params
  		params.require(:comment).permit(:content)
  	end

end

login2/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@posts = Post.all
  end
end

login2/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
		@post = Post.new
	end
	def show
		@post = Post.find(params[:id])
	end
	
	def create
		@post = current_user.posts.create(post_params)

		if @post.save
			#ExampleMailer.sample_email(@user).deliver
			redirect_to posts_path
		else
			flash[:notice]= "Post can't be blank"
			redirect_to posts_path
		end
	end

	def current_user
		User.find(session[:user_id])
	end

	def destroy 
		#puts "PARAM ID: " + params[:id]
		post = current_user.posts.find_by(id: params[:id])
		if post
			flash[:notice] = "You delete successfully"
			post.destroy
		else
			flash[:notice] = "You can't delete this post!"
		end
		redirect_to posts_path
	end

	def edit 
		post = current_user.posts.find_by(id: params[:id])
		if post.update(post_params)
			flash[:notice] = "You update successfully"
		else
			flash[:notice] = "You can't delete this post!"
		end
		redirect_to posts_path
	end

	private
	def post_params
		params.require(:post).permit(:content)
	end
end

login2/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if (user && user.password == params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "You login success."
      redirect_to root_path
    else
      flash[:notice] = "Email or password is false."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

login2/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def sign_up
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			#ExampleMailer.sample_email(@user).deliver
			redirect_to root_path
		else
			render :sign_up
		end
	end

	def sign_in
	end

	private
	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :password)
	end
end

login2/app/helpers/application_helper.rb
module ApplicationHelper
end

login2/app/helpers/comments_helper.rb
module CommentsHelper
end

login2/app/helpers/home_helper.rb
module HomeHelper
end

login2/app/helpers/posts_helper.rb
module PostsHelper
end

login2/app/helpers/sessions_helper.rb
module SessionsHelper
end

login2/app/helpers/users_helper.rb
module UsersHelper
end

login2/app/views/comments/index.html.erb
<div id="comment">
<div class="container">
	<div class="row">
		<div class="center mid">
			<div class="user-info border">
				<p class="block"></p>
				<img src="<%= asset_path( 'user-image.png' ) %>" alt="" class="img img-rounded img-responsive pull-right border button-right" style="width:25px; border-radius: 100%;padding:2px;">
			</div>
			<div class="middle">
				<div class="media border biggerdiv">
					<div class="media-left">
						<img src="<%= asset_path( 'user-image.png' ) %>" class="media-object" style="width:25px">
					</div>
					<div class="media-body">
						<h4 class="media-heading"><%= @user.first_name + " " + @user.last_name %></h4>
						<p><%= @post.content %></p>
					</div>
				</div>

				<% flash.each do |key, value| %>
				<div class="alert-green alert-<%= key %>"><%= value %></div>
				<% end %>


		
				<%= form_for [@post, @comment], html: { class: "form_comment" } do |f|  %>
				  <%= f.text_area :content, placeholder: "Add content..." , class:"border" %><br />

				  <%= f.submit class:"btn btn-default border button-right pull-right", value:"Comment"%>

				<% end %>
				
				<%if @comments %>
					<% @comments.each do |comment| %>

						<div class="media border">
							<div class="media-left">
								<img src="<%= asset_path( 'user-image.png' ) %>" class="media-object" style="width:25px">
							</div>
							<div class="media-body">
								<h4 class="media-heading"><%= @current_user.first_name + " " + @current_user.last_name %></h4>
								<p><%= comment.content %></p>
							</div>
						</div>
					<%end%>
				<% else %>
					<p>Not found any comment!</p>
				<% end %>
			</div>
		</div>
	</div>
</div>
</div>

login2/app/views/comments/new.html.erb
<h1> new comment page </h1>

login2/app/views/comments/show.html.erb
<h1> Show page </h1>

<% if @post %>
	<p><% @post.id %></p>
	<p><% @post.content %></p>
<%end%>

login2/app/views/home/index.html.erb
<% flash.each do |key, value| %>
<div class="alert-green alert-<%= key %>"><%= value %></div>
<% end %>
<div class="container">
	<div class="row">
		<div class="center mid">
			<div class="user-info border">
				<p class="block"><%=session[:user_id]%></p>
				<img src="<%= asset_path( 'user-image.png' ) %>" alt="" class="img img-rounded img-responsive pull-right border" style="width:25px; border-radius: 100%;padding:2px;">
			</div>
			<div class="middle">
				<%= form_for @post, as: :post, url: posts_path, html: { class: "form_post" } do |f|  %>
				  <%= text_area :content, html: {placeholder: "Add content..."} %><br />

				  <%= f.submit class:"btn btn-default"%>
				<% end %>
				
				<%if @posts %>
					<% @posts.each do |post| %>
						<div class="media border">
							<div class="media-left">
								<img src="<%= asset_path( 'user-image.png' ) %>" class="media-object" style="width:25px">
							</div>
							<div class="media-body">
								<h4 class="media-heading"><%= post.user.first_name + " " + post.user.last_name %></h4>
								<p><%= post.content %></p>
							</div>
						</div>
					<%end%>
				<% else %>
					<p>Not found any post!</p>
				<% end %>
			</div>
		</div>
	</div>
</div>

login2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login-Signup-WelcomeEmail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

login2/app/views/posts/index.html.erb
<div id="post">
<div class="container" >
	<div class="row">
		<div class="center mid">
			<div class="user-info border">
				<p class="block"></p>
				<img src="<%= asset_path( 'user-image.png' ) %>" alt="" class="img img-rounded img-responsive pull-right border" style="width:25px; border-radius: 100%;padding:2px;">
			</div>
			<div class="middle">
				<%= form_for @post, as: :post, html: { class: "form_post" } do |f|  %>
				  <%= f.text_area :content, placeholder: "Add content..."  %><br />

				  <%= f.submit class:"btn btn-default button-right border pull-right"%>


				<% end %>
				
				<% flash.each do |key, value| %>

					<div class="alert alert-info"><%= value %></div>
				<% end %>
				
				<%if @posts %>
					<% @posts.each do |post| %>

						<div class="media border">
							<div class="media-left">
								<img src="<%= asset_path( 'user-image.png' ) %>" class="media-object" style="width:25px">
							</div>
							<div class="media-body">
								<h4 class="media-heading"><%= post.user.first_name + " " + post.user.last_name %></h4>
								<p><%= post.content %></p>
							</div>
							<p><%= link_to 'Comment this post', post_comments_path(post) %> | 
							<%= link_to 'Delete this post', post, :method => :delete, :confirm => "You sure?",
                                :title => "Delete #{post.content}" %> 
                                </p>
						</div>
					<%end%>
				<% else %>
					<p>Not found any post!</p>
				<% end %>
			</div>
		</div>
	</div>
</div>
</div>

login2/app/views/posts/new.html.erb
<p>You want to create a POST</p>

login2/app/views/posts/show.html.erb
<h5>Content: </h5>
<p><%= @post.content %></p>
<p></p>

login2/app/views/users/sign_in.html.erb
<div class="container sign-up">
	<div class="row">
		<div class="title">
			<h4>SIGN IN</h4>
		</div>
	</div>
	<div class="row">

		<div class="sign-up-form col-md-4 col-md-offset-4">
			<%= form_for :session,url: login_path, class: "form-horizontal" do |f| %>
				<div class="form-group">
					<label class="control-label">Email</label>
					<%= f.text_field :email, class: "form-control" %>
				</div>
				<div class="form-group">
					<label class="control-label">Password</label>
					<%= f.password_field :password, class: "form-control" %>
				</div>
				<div class="action">
					<%= f.submit class: "btn btn-primary btn-center" %>
          <div class="row">
            Don't have account<%= link_to "Sign Up", login_path, class: "btn btn-link" %>
          </div>
				</div>
			<% end %>
		</div>
	</div>
</div>

login2/app/views/users/sign_up.html.erb
<div class="container sign-up">
	<div class="row">
		<div class="title">
			<h4>SIGN UP FORM</h4>
		</div>
	</div>
	<div class="row">
		<% if @user.errors.any? %>
			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		<% end %>
		<div class="sign-up-form col-md-4 col-md-offset-4">
			<%= form_for @user, class: "form-horizontal" do |f| %>
				<div class="form-group">
					<label class="control-label">First name</label>
					<%= f.text_field :first_name, class: "form-control" %>
				</div>
				<div class="form-group">
					<label class="control-label">Last name</label>
					<%= f.text_field :last_name, class: "form-control" %>
				</div>
				<div class="form-group">
					<label class="control-label">Email</label>
					<%= f.text_field :email, class: "form-control" %>
				</div>
				<div class="form-group">
					<label class="control-label">Password</label>
					<%= f.password_field :password, class: "form-control" %>
				</div>
				<div class="action">
					<%= f.submit class: "btn btn-primary" %>
						.<div class="row">
							Already have an account
							<%= link_to "Sign In", login_path, class: "btn btn-link" %>
						</div>
				</div>
			<% end %>
		</div>
	</div>
</div>